name: build-test

on:
  push:
    branches: [ rewrite ]
  pull_request:
    branches: [ rewrite ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install nightly
      run: rustup install nightly

    - name: Build
      run: cargo +nightly build --verbose

    - name: Run tests
      run: cargo _nightly test --verbose
