name: build-test-bench

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
        matrix:
          os: [macos-latest, ubuntu-latest]
          include:
          - os: macos-latest
            INSTALL_LLVM: brew install llvm
          - os: ubuntu-latest
            INSTALL_LLVM: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 10
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install LLVM
      run: ${{matrix.INSTALL_LLVM}}
    - name: Get rust nightly
      run: rustup install nightly
    - name: Set rust nightly as default for cargo
      run: rustup default nightly
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run becnhmarks
      run: cargo bench --verbose
